// core/project_serializer.js
// Author: CCVO
// Purpose:
// Serialize the entire in-memory project into a valid Godot 4.x project layout.
// Output must unzip and open cleanly in Godot without manual fixes.

class ProjectSerializer {
    constructor(projectGraph, assetHandler) {
        this.graph = projectGraph;
        this.assets = assetHandler;
        this.sceneSerializer = new SceneSerializer(projectGraph);
    }

    // =====================================================
    // Public API
    // =====================================================

    async exportProject(projectName = "GodotGame") {
        if (!window.JSZip) {
            throw new Error("JSZip not loaded");
        }

        const zip = new JSZip();

        // Root folders
        zip.folder(".godot");
        zip.folder("scenes");
        zip.folder("scripts");
        zip.folder("assets");

        // ---- project.godot ----
        zip.file(
            "project.godot",
            this._generateProjectGodot(projectName)
        );

        // ---- Scenes ----
        for (const sceneName of this.graph.getScenes()) {
            const tscn = this.sceneSerializer.serializeScene(sceneName);
            zip.file(`scenes/${sceneName}.tscn`, tscn);
        }

        // ---- Scripts ----
        const scripts = this._collectScripts();
        for (const script of scripts) {
            zip.file(`scripts/${script.name}.gd`, script.code);
        }

        // ---- Assets ----
        for (const path in this.assets.assets) {
            const asset = this.assets.assets[path];
            if (asset.data) {
                zip.file(`assets/${path}`, asset.data, { binary: true });
            }
        }

        // ---- Download ----
        const blob = await zip.generateAsync({ type: "blob" });
        this._downloadBlob(blob, `${projectName}.zip`);
    }

    // =====================================================
    // Internal Helpers
    // =====================================================

    _generateProjectGodot(projectName) {
        return `
; Engine configuration file.
; Generated by Godot Game Assembler

config_version=5

[application]
config/name="${projectName}"
run/main_scene="res://scenes/${this._defaultScene()}.tscn"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720
window/handheld/orientation="portrait"

[input]
ui_accept={
"deadzone": 0.5,
"events": [ Object(InputEventKey,"keycode":4194309) ]
}
`.trim();
    }

    _defaultScene() {
        const scenes = this.graph.getScenes();
        return scenes.length ? scenes[0] : "main";
    }

    _collectScripts() {
        const scripts = [];
        for (const sceneName of this.graph.getScenes()) {
            const scene = this.graph.getScene(sceneName);
            for (const nodeName in scene.nodes) {
                const node = scene.nodes[nodeName];
                for (const script of node.scripts || []) {
                    scripts.push({
                        name: script,
                        code: this._defaultScriptTemplate(script)
                    });
                }
            }
        }
        return scripts;
    }

    _defaultScriptTemplate(name) {
        return `
extends Node

func _ready():
    pass
`.trim();
    }

    _downloadBlob(blob, filename) {
        const a = document.createElement("a");
        a.href = URL.createObjectURL(blob);
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(a.href);
    }
}

// Expose globally
window.ProjectSerializer = ProjectSerializer;

console.log("ProjectSerializer loaded.");
